services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todos
  
  api:
    build:
      context: .
    depends_on: 
    - postgres
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=Host=postgres;Port=5432;Username=postgres;Password=12345;Database=todos;
