name: Matrix Example

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        folder: ['python-pip', 'python-poetry']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          echo "Building ${{ matrix.folder }}"
          cd ${{ matrix.folder }}
          docker compose up -d
          cd ../tests
          pip install requests
          python test_api.py
      - name: Cleanup
        if: always()
        run: |
          cd ${{ matrix.folder }}
          docker compose down

